// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import CameraController from "./camera_controller"
application.register("camera", CameraController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import QrScannerController from "./qr_scanner_controller"
application.register("qr-scanner", QrScannerController)

import PhotoViewerController from "./photo_viewer_controller"
application.register("photoviewer", PhotoViewerController)

import PushNotificationController from "./push_notification_controller"
application.register("push-notification", PushNotificationController)
